/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;

import com.bean.Micro;
import com.dao.MicroJpaDAO;
import com.utils.Tabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thiago.napoleao
 */
public class FrameMetas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public FrameMetas() {
       initComponents();
        defaults();
    }
    
     public void defaults(){
        tabela();
        microTxt.requestFocus(true);
    }
    
     public void cadastro(){
        
     Micro rt = new Micro();
     rt.setMicro(microTxt.getText());
     rt.setMeta(metaTxt.getText());
     MicroJpaDAO.getInstance().persist(rt);
     tabela();
     
     microTxt.setText("");
     metaTxt.setText("");
     microTxt.requestFocus();
    }
    
      public void excluir(){
        
        int idProduto = (int) tblRoteiros.getValueAt(tblRoteiros.getSelectedRow(), tblRoteiros.getSelectedColumn());
        
        MicroJpaDAO.getInstance().removeById(idProduto);
        System.out.println("Linha removida...");
        
        tabela();
        System.out.println("Tabela atualizada...");
        
    }
    
    
     public void tabela(){
        try{
           ArrayList dados = new ArrayList();
           String[] Colunas = new String[]{"Id" ,"Computador", "Meta"};
           List<Micro> rt = MicroJpaDAO.getInstance().findAll();
           for(int b = 0; b < rt.size(); b ++){
               dados.add(new Object[]{rt.get(b).getId(), rt.get(b).getMicro(), rt.get(b).getMeta()});
           }
           Tabela tabela = new Tabela(dados, Colunas);
           tblRoteiros.setModel(tabela);
           tblRoteiros.setRowSorter(new TableRowSorter(tabela));
           tblRoteiros.getColumnModel().getColumn(0).setPreferredWidth(100);
           tblRoteiros.getColumnModel().getColumn(0).setResizable(false);
           tblRoteiros.getColumnModel().getColumn(1).setPreferredWidth(100);
           tblRoteiros.getColumnModel().getColumn(1).setResizable(false);
           tblRoteiros.getColumnModel().getColumn(2).setPreferredWidth(100);
           tblRoteiros.getColumnModel().getColumn(2).setResizable(false);
           tblRoteiros.getTableHeader().setReorderingAllowed(false);
           tblRoteiros.setAutoResizeMode(tblRoteiros.AUTO_RESIZE_OFF);
           tblRoteiros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                       
        }catch(Exception ex){
          ex.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblH10 = new javax.swing.JLabel();
        microTxt = new javax.swing.JTextField();
        lblH11 = new javax.swing.JLabel();
        metaTxt = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoteiros = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblMensagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 33, 71));

        lblH10.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblH10.setForeground(new java.awt.Color(255, 255, 255));
        lblH10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH10.setText("Computador");
        lblH10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        microTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        microTxt.setForeground(new java.awt.Color(0, 51, 102));
        microTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        microTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                microTxtKeyReleased(evt);
            }
        });

        lblH11.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblH11.setForeground(new java.awt.Color(255, 255, 255));
        lblH11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH11.setText("Meta");
        lblH11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        metaTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        metaTxt.setForeground(new java.awt.Color(0, 51, 102));
        metaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        metaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                metaTxtKeyReleased(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblRoteiros.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        tblRoteiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRoteiros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblRoteiros.setGridColor(new java.awt.Color(255, 255, 255));
        tblRoteiros.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblRoteiros);

        lblMensagem.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("Cadastro das Metas por Computador");

        jDesktopPane1.setLayer(lblMensagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo15.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 1, 55)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblH11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(microTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(metaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel4)))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(microTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblH11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(metaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 326, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void microTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_microTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            try {
                tabela();
                metaTxt.requestFocus(true);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_microTxtKeyReleased

    private void metaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_metaTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_metaTxtKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        cadastro();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblH10;
    private javax.swing.JLabel lblH11;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField metaTxt;
    private javax.swing.JTextField microTxt;
    private javax.swing.JTable tblRoteiros;
    // End of variables declaration//GEN-END:variables
}
