/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;

import com.bean.Login;
import com.dao.LoginJpaDAO;
import com.utils.DataHora;
import com.utils.Tabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thiago.napoleao
 */
public class FrameCadastro extends javax.swing.JPanel {
  
     DataHora dataHora;
    /**
     * Creates new form FrameCadastr
     */
    public FrameCadastro() {
     initComponents();   
     defaut();  
      matriculaTxt.requestFocus(true);
      
    }
    
    public void defaut(){
     matriculaTxt.requestFocus(true);
     tabela();
    }
    
    
    public void cadastro(){
        DataHora hora = new DataHora();  
        Login log = new Login();    
        log.setUser(matriculaTxt.getText());
        log.setNome(conferenteTxt.getText().toUpperCase());
        log.setPassword("novousuario");
        log.setData_cadastro(hora.Data());
        log.setRole(roleTxt.getText());
        LoginJpaDAO.getInstance().persist(log);
        
        
        tabela();
        matriculaTxt.setText("");
        conferenteTxt.setText("");
        matriculaTxt.requestFocus(true);
    }
    
    
    public void verifiqueUsuario(){
      
        List<Login> log = LoginJpaDAO.getInstance().findAll();
        String matricula = "";
        
        for(int b = 0; b < log.size(); b ++){
          
         String tempMat = "";
         tempMat = log.get(b).getUser().replace("", "");
         tempMat.replace("", "");
         matricula = tempMat;
         
         if(matriculaTxt.getText().toUpperCase().equals(matricula)){
             JOptionPane.showMessageDialog(null, "Matricula já cadastrada!");    
             break;
         }
           conferenteTxt.requestFocus(true);
        }
        
        
    }
    
    
    public void tabela(){
        try{
           ArrayList dados = new ArrayList();
           String[] Colunas = new String[]{"Codigo","Matricula", "Usuario", "Data de Cadastro"};
           List<Login> rt = LoginJpaDAO.getInstance().findAll();
           for(int b = 0; b < rt.size(); b ++){
               dados.add(new Object[]{rt.get(b).getId(), rt.get(b).getUser(), rt.get(b).getNome(), rt.get(b).getData_cadastro()});
           }
           Tabela tabela = new Tabela(dados, Colunas);
           tblRoteiros.setModel(tabela);
           tblRoteiros.setRowSorter(new TableRowSorter(tabela));
           tblRoteiros.getColumnModel().getColumn(0).setPreferredWidth(80);
           tblRoteiros.getColumnModel().getColumn(0).setResizable(false);
           tblRoteiros.getColumnModel().getColumn(1).setPreferredWidth(120);
           tblRoteiros.getColumnModel().getColumn(1).setResizable(false);
           tblRoteiros.getColumnModel().getColumn(2).setPreferredWidth(340);
           tblRoteiros.getColumnModel().getColumn(2).setResizable(false);
           tblRoteiros.getColumnModel().getColumn(3).setPreferredWidth(180);
           tblRoteiros.getColumnModel().getColumn(3).setResizable(false);
           tblRoteiros.getTableHeader().setReorderingAllowed(false);
           tblRoteiros.setAutoResizeMode(tblRoteiros.AUTO_RESIZE_OFF);
           tblRoteiros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                       
        }catch(Exception ex){
          ex.printStackTrace();
        }
      }

    
     public void excluirDados() {
        /**
         * getValueAt devolve o valor de uma linha/coluna no principio de por exemplo : linha 1 coluna 1
         * getSelectedRow() devolve um valor int com numero indice da linha selecionada
         * getSelectedColumn() devolve um valor int com numero indice da coluna selecionada
         */
        int idUser =  (int) tblRoteiros.getValueAt(tblRoteiros.getSelectedRow(), tblRoteiros.getSelectedColumn());
        
        LoginJpaDAO.getInstance().removeById(idUser);
        System.out.println("Linha removida...");
        
        tabela();
        System.out.println("Tabela atualizada...");
        
    }
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblH10 = new javax.swing.JLabel();
        matriculaTxt = new javax.swing.JTextField();
        conferenteTxt = new javax.swing.JTextField();
        lblH13 = new javax.swing.JLabel();
        lblH14 = new javax.swing.JLabel();
        roleTxt = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoteiros = new javax.swing.JTable();

        setBackground(new java.awt.Color(18, 33, 71));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Conferente");

        jDesktopPane5.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 1, 55)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo15.png"))); // NOI18N

        lblH10.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblH10.setForeground(new java.awt.Color(255, 255, 255));
        lblH10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH10.setText("Matricula");
        lblH10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        matriculaTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        matriculaTxt.setForeground(new java.awt.Color(0, 51, 102));
        matriculaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matriculaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculaTxtKeyReleased(evt);
            }
        });

        conferenteTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        conferenteTxt.setForeground(new java.awt.Color(0, 51, 102));
        conferenteTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conferenteTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conferenteTxtKeyReleased(evt);
            }
        });

        lblH13.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblH13.setForeground(new java.awt.Color(255, 255, 255));
        lblH13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH13.setText("Conferente");
        lblH13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblH14.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        lblH14.setForeground(new java.awt.Color(255, 255, 255));
        lblH14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH14.setText("Acesso");
        lblH14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        roleTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        roleTxt.setForeground(new java.awt.Color(0, 51, 102));
        roleTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roleTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roleTxtKeyReleased(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblRoteiros.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        tblRoteiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRoteiros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblRoteiros.setGridColor(new java.awt.Color(255, 255, 255));
        tblRoteiros.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblRoteiros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(matriculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conferenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH13, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addComponent(jDesktopPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matriculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblH13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conferenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblH14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            try {
                verifiqueUsuario();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_matriculaTxtKeyReleased

    private void conferenteTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conferenteTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            try {
                roleTxt.requestFocus(true);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_conferenteTxtKeyReleased

    private void roleTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roleTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            try {
                cadastro();
            } catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_roleTxtKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        verifiqueUsuario();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluirDados();
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField conferenteTxt;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblH10;
    private javax.swing.JLabel lblH13;
    private javax.swing.JLabel lblH14;
    private javax.swing.JTextField matriculaTxt;
    private javax.swing.JTextField roleTxt;
    private javax.swing.JTable tblRoteiros;
    // End of variables declaration//GEN-END:variables
}
